name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.400' # 使用更稳定的 .NET SDK 版本
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 16.0 # Visual Studio 2019, which includes .NET Framework 4.5
    
    - name: Install .NET Framework 4.5 SDK
      run: |
        Start-Process -Wait -FilePath "https://download.microsoft.com/download/b/a/4/ba4a7e71-2996-499b-a91a-011086264719/netfx_dt_x64.exe" -ArgumentList "/q"
    
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Modify project files
      run: |
        $projectFiles = @(
          "ConfuserExKiller\ConfuserExKiller.csproj",
          "ProxyKiller\ProxyKiller.csproj",
          "ConstantKiller\ConstantKiller.csproj"
        )
        foreach ($projectFile in $projectFiles) {
          $content = Get-Content $projectFile
          $content = $content -replace '<TargetFrameworkVersion>v3.5</TargetFrameworkVersion>', '<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>'
          $content = $content -replace '<TargetFramework>net35</TargetFramework>', '<TargetFramework>net45</TargetFramework>'
          Set-Content $projectFile -Value $content
        }
        
        # 检查并修改 packages.config 文件
        $packagesFiles = @(
            "ConfuserExKiller\packages.config",
            "ProxyKiller\packages.config",
            "ConstantKiller\packages.config"
        )
        foreach ($packagesFile in $packagesFiles) {
            if (Test-Path $packagesFile) {
                $content = Get-Content $packagesFile
                $content = $content -replace 'targetFramework="net35"', 'targetFramework="net45"'
                Set-Content $packagesFile -Value $content
            }
        }
    
    - name: Clean build output
      run: dotnet clean ConfuserExTools.sln

    - name: Restore dependencies
      run: dotnet restore ConfuserExTools.sln

    - name: Build
      run: dotnet build ConfuserExTools.sln -c Release -v detailed

    - name: Publish
      run: dotnet publish ConfuserExTools.sln -c Release -r win-x64 --self-contained true -f net45 -o publish -v detailed

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ConfuserExTools-win-x64
        path: publish 
