name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # 根据项目需要调整 .NET SDK 版本

    - name: Modify project files
      run: |
        $projectFiles = @(
          "ConfuserExKiller\ConfuserExKiller.csproj",
          "ProxyKiller\ProxyKiller.csproj",
          "ConstantKiller\ConstantKiller.csproj"
        )
        foreach ($projectFile in $projectFiles) {
          $content = Get-Content $projectFile
          $content = $content -replace '<TargetFrameworkVersion>v3.5</TargetFrameworkVersion>', '<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>'
          Set-Content $projectFile -Value $content
        }

    - name: Restore dependencies
      run: dotnet restore ConfuserExTools.sln

    - name: Build
      run: dotnet build ConfuserExTools.sln -c Release

    - name: Publish
      run: dotnet publish ConfuserExTools.sln -c Release -r win-x64 --self-contained true -o publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ConfuserExTools-win-x64
        path: publish 
